# Generated by Django 3.1.5 on 2021-01-26 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('10', 'Improvement'), ('20', 'Trivial'), ('30', 'Less'), ('50', 'Normal'), ('70', 'Major'), ('90', 'Critical')], default='10', max_length=2)),
                ('stage', models.CharField(choices=[('20', 'Registered'), ('40', 'Accepted'), ('60', 'Working on'), ('80', 'Closed')], default='20', max_length=2)),
                ('opening_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('keywords', models.TextField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, max_length=200, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Btapp.project')),
            ],
        ),
    ]
