# Generated by Django 3.1.5 on 2021-01-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Btapp', '0002_auto_20210127_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='stage',
            field=models.CharField(choices=[('20', 'Registered'), ('60', 'Working on'), ('80', 'Closed')], default='20', max_length=2),
        ),
    ]
