# Generated by Django 3.1.5 on 2021-02-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Btapp', '0007_auto_20210212_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
