# Generated by Django 3.1.5 on 2021-02-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Btapp', '0009_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('ticket', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
    ]
