# Generated by Django 3.1.5 on 2021-02-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Btapp', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
