# Generated by Django 3.1.5 on 2021-02-24 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Btapp', '0013_auto_20210223_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='Btapp.project'),
        ),
    ]
