# Generated by Django 3.1.5 on 2021-03-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Btapp', '0014_auto_20210223_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='summary',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
