# Generated by Django 3.1.5 on 2021-02-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Btapp', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
