# Generated by Django 3.1.5 on 2021-02-13 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Btapp', '0006_auto_20210212_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='registration_date',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='project',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
